import * as THREE from './vendor/three.module.js';
const host=document.getElementById('scene'),button=document.getElementById('motion'),hint=document.getElementById('scene-hint'),coords=document.getElementById('coords');
try {
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true,frame=0,last=0,elapsed=0;
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x000000,0);host.appendChild(renderer.domElement);host.classList.add('ready');
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020805,.035);const camera=new THREE.PerspectiveCamera(42,1,.1,80);camera.position.z=14;
const core=new THREE.Group();scene.add(core);const green=0x79f596;
const shell=new THREE.LineSegments(new THREE.WireframeGeometry(new THREE.IcosahedronGeometry(1.7,1)),new THREE.LineBasicMaterial({color:green,transparent:true,opacity:.66}));core.add(shell);
const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(1.13,0),new THREE.MeshBasicMaterial({color:0x153d23,transparent:true,opacity:.38}));core.add(inner);
const innerEdges=new THREE.LineSegments(new THREE.EdgesGeometry(inner.geometry),new THREE.LineBasicMaterial({color:0xb8ffc8,transparent:true,opacity:.8}));core.add(innerEdges);
const rings=[];for(let n=0;n<3;n++){const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1+n*.19,.009,4,160),new THREE.MeshBasicMaterial({color:n===1?0xd0ffdc:green,transparent:true,opacity:.35+n*.12}));ring.rotation.set(Math.PI/2+n*.5,.3+n*.6,n*.4);core.add(ring);rings.push(ring)}
const small=matchMedia('(max-width:650px)').matches,count=small?550:1100,positions=new Float32Array(count*3),base=new Float32Array(count*3),colors=new Float32Array(count*3);let seed=1937;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}for(let i=0;i<count;i++){const j=i*3;positions[j]=base[j]=(random()-.5)*28;positions[j+1]=base[j+1]=(random()-.5)*18;positions[j+2]=base[j+2]=-random()*14;colors[j]=.25+random()*.35;colors[j+1]=.6+random()*.4;colors[j+2]=.35+random()*.3}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));const particles=new THREE.Points(geo,new THREE.PointsMaterial({size:.042,vertexColors:true,transparent:true,opacity:.8,sizeAttenuation:true}));scene.add(particles);
const grid=new THREE.GridHelper(70,42,0x337b45,0x12381f);grid.position.set(0,-4.5,-10);grid.material.transparent=true;grid.material.opacity=.35;scene.add(grid);
const trailCount=32,trailArray=new Float32Array(trailCount*3),trailGeo=new THREE.BufferGeometry();trailGeo.setAttribute('position',new THREE.BufferAttribute(trailArray,3));const trail=new THREE.Line(trailGeo,new THREE.LineBasicMaterial({color:0x92ffab,transparent:true,opacity:.65}));scene.add(trail);const reticle=new THREE.Mesh(new THREE.RingGeometry(.06,.085,24),new THREE.MeshBasicMaterial({color:0xb0ffbe,transparent:true,opacity:.8,side:THREE.DoubleSide}));scene.add(reticle);
const target=new THREE.Vector2(),smooth=new THREE.Vector2(),cursor=new THREE.Vector3(),home=new THREE.Vector3();let mobile=false,spanX=10,spanY=7,active=false;
function resize(){const w=host.clientWidth,h=host.clientHeight;mobile=w<650;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();spanY=2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.position.z;spanX=spanY*camera.aspect;home.set(mobile?0:spanX*.255,mobile?-spanY*.245:0,0);core.scale.setScalar(mobile?.66:1);if(paused)draw(0)}
function move(e){const r=host.getBoundingClientRect();target.set(THREE.MathUtils.clamp((e.clientX-r.left)/r.width*2-1,-1,1),THREE.MathUtils.clamp(-((e.clientY-r.top)/r.height*2-1),-1,1));active=e.clientY>=r.top&&e.clientY<=r.bottom;coords.textContent='X '+target.x.toFixed(2)+'  Y '+target.y.toFixed(2)}window.addEventListener('pointermove',move,{passive:true});window.addEventListener('pointerdown',move,{passive:true});
function draw(dt){smooth.lerp(target,1-Math.exp(-5*Math.max(dt,.016)));core.position.set(home.x+smooth.x*.65,home.y+smooth.y*.5,0);core.rotation.set(smooth.y*.24+elapsed*.07,smooth.x*.38+elapsed*.12,elapsed*.03);inner.rotation.y=-elapsed*.22;innerEdges.rotation.copy(inner.rotation);rings.forEach((ring,i)=>{ring.rotation.z=elapsed*(i%2?.12:-.1)+i*.4});camera.position.x=smooth.x*.3;camera.position.y=smooth.y*.2;camera.lookAt(0,0,0);cursor.set(smooth.x*spanX*.5,smooth.y*spanY*.5,0);reticle.position.copy(cursor);reticle.visible=trail.visible=active&&!mobile;for(let i=trailCount-1;i>0;i--){let j=i*3,k=(i-1)*3;trailArray[j]+=(trailArray[k]-trailArray[j])*.6;trailArray[j+1]+=(trailArray[k+1]-trailArray[j+1])*.6}trailArray[0]=cursor.x;trailArray[1]=cursor.y;trailGeo.attributes.position.needsUpdate=true;for(let i=0;i<count;i++){const j=i*3,dx=base[j]-cursor.x,dy=base[j+1]-cursor.y,d=dx*dx+dy*dy,force=active?Math.exp(-d*.45)*.7:0;positions[j]=base[j]+dx*force;positions[j+1]=base[j+1]+Math.sin(elapsed*.3+i)*.075+dy*force}geo.attributes.position.needsUpdate=true;renderer.render(scene,camera)}
function loop(now){frame=0;if(paused||!visible||document.hidden)return;const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;draw(dt);frame=requestAnimationFrame(loop)}function start(){if(!frame&&!paused&&visible&&!document.hidden){last=performance.now();frame=requestAnimationFrame(loop)}}function sync(){button.textContent=paused?'Ativar movimento':'Pausar movimento';button.setAttribute('aria-pressed',String(paused));if(paused){cancelAnimationFrame(frame);frame=0;draw(0)}else start()}button.addEventListener('click',()=>{paused=!paused;sync()});reduced.addEventListener('change',e=>{paused=e.matches;sync()});new ResizeObserver(resize).observe(host);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)start();else{cancelAnimationFrame(frame);frame=0}}).observe(host);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0}else start()});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);frame=0;host.classList.remove('ready');button.hidden=true;hint.textContent='A cena 3D foi pausada pelo navegador.'});if(matchMedia('(pointer:coarse)').matches)hint.textContent='Toque na cena para mover o núcleo.';resize();sync();
} catch(error){button.hidden=true;hint.textContent='Explore os projetos e o terminal abaixo.';console.warn('Cena 3D indisponível',error)}
